# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x61i.proto\x12\x02\x61i\"\x1c\n\x0b\x43hatRequest\x12\r\n\x05query\x18\x01 \x01(\t\"+\n\x15RecommendationRequest\x12\x12\n\nquery_text\x18\x01 \x01(\t\"%\n\rSearchRequest\x12\x14\n\x0csearch_query\x18\x01 \x01(\t\"\x1b\n\tChatReply\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\".\n\x13RecommendationReply\x12\x17\n\x0frecommended_ids\x18\x01 \x03(\t2\x9f\x02\n\tAIService\x12\x36\n\x12GetChatbotResponse\x12\x0f.ai.ChatRequest\x1a\r.ai.ChatReply\"\x00\x12N\n\x16GetUserRecommendations\x12\x19.ai.RecommendationRequest\x1a\x17.ai.RecommendationReply\"\x00\x12J\n\x12GetRelatedProjects\x12\x19.ai.RecommendationRequest\x1a\x17.ai.RecommendationReply\"\x00\x12>\n\x0eSearchProjects\x12\x11.ai.SearchRequest\x1a\x17.ai.RecommendationReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATREQUEST']._serialized_start=16
  _globals['_CHATREQUEST']._serialized_end=44
  _globals['_RECOMMENDATIONREQUEST']._serialized_start=46
  _globals['_RECOMMENDATIONREQUEST']._serialized_end=89
  _globals['_SEARCHREQUEST']._serialized_start=91
  _globals['_SEARCHREQUEST']._serialized_end=128
  _globals['_CHATREPLY']._serialized_start=130
  _globals['_CHATREPLY']._serialized_end=157
  _globals['_RECOMMENDATIONREPLY']._serialized_start=159
  _globals['_RECOMMENDATIONREPLY']._serialized_end=205
  _globals['_AISERVICE']._serialized_start=208
  _globals['_AISERVICE']._serialized_end=495
# @@protoc_insertion_point(module_scope)
