# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ai_pb2 as ai__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetChatbotResponse = channel.unary_unary(
                '/ai.AIService/GetChatbotResponse',
                request_serializer=ai__pb2.ChatRequest.SerializeToString,
                response_deserializer=ai__pb2.ChatReply.FromString,
                _registered_method=True)
        self.GetUserRecommendations = channel.unary_unary(
                '/ai.AIService/GetUserRecommendations',
                request_serializer=ai__pb2.RecommendationRequest.SerializeToString,
                response_deserializer=ai__pb2.RecommendationReply.FromString,
                _registered_method=True)
        self.GetRelatedProjects = channel.unary_unary(
                '/ai.AIService/GetRelatedProjects',
                request_serializer=ai__pb2.RecommendationRequest.SerializeToString,
                response_deserializer=ai__pb2.RecommendationReply.FromString,
                _registered_method=True)
        self.SearchProjects = channel.unary_unary(
                '/ai.AIService/SearchProjects',
                request_serializer=ai__pb2.SearchRequest.SerializeToString,
                response_deserializer=ai__pb2.RecommendationReply.FromString,
                _registered_method=True)
        self.IndexNewData = channel.unary_unary(
                '/ai.AIService/IndexNewData',
                request_serializer=ai__pb2.Empty.SerializeToString,
                response_deserializer=ai__pb2.IndexReply.FromString,
                _registered_method=True)
        self.DeleteProjectFromIndex = channel.unary_unary(
                '/ai.AIService/DeleteProjectFromIndex',
                request_serializer=ai__pb2.DeleteProjectRequest.SerializeToString,
                response_deserializer=ai__pb2.IndexingResponse.FromString,
                _registered_method=True)


class AIServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetChatbotResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserRecommendations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRelatedProjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchProjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IndexNewData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProjectFromIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetChatbotResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChatbotResponse,
                    request_deserializer=ai__pb2.ChatRequest.FromString,
                    response_serializer=ai__pb2.ChatReply.SerializeToString,
            ),
            'GetUserRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserRecommendations,
                    request_deserializer=ai__pb2.RecommendationRequest.FromString,
                    response_serializer=ai__pb2.RecommendationReply.SerializeToString,
            ),
            'GetRelatedProjects': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRelatedProjects,
                    request_deserializer=ai__pb2.RecommendationRequest.FromString,
                    response_serializer=ai__pb2.RecommendationReply.SerializeToString,
            ),
            'SearchProjects': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchProjects,
                    request_deserializer=ai__pb2.SearchRequest.FromString,
                    response_serializer=ai__pb2.RecommendationReply.SerializeToString,
            ),
            'IndexNewData': grpc.unary_unary_rpc_method_handler(
                    servicer.IndexNewData,
                    request_deserializer=ai__pb2.Empty.FromString,
                    response_serializer=ai__pb2.IndexReply.SerializeToString,
            ),
            'DeleteProjectFromIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProjectFromIndex,
                    request_deserializer=ai__pb2.DeleteProjectRequest.FromString,
                    response_serializer=ai__pb2.IndexingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.AIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetChatbotResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/GetChatbotResponse',
            ai__pb2.ChatRequest.SerializeToString,
            ai__pb2.ChatReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/GetUserRecommendations',
            ai__pb2.RecommendationRequest.SerializeToString,
            ai__pb2.RecommendationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRelatedProjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/GetRelatedProjects',
            ai__pb2.RecommendationRequest.SerializeToString,
            ai__pb2.RecommendationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchProjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/SearchProjects',
            ai__pb2.SearchRequest.SerializeToString,
            ai__pb2.RecommendationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IndexNewData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/IndexNewData',
            ai__pb2.Empty.SerializeToString,
            ai__pb2.IndexReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProjectFromIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/DeleteProjectFromIndex',
            ai__pb2.DeleteProjectRequest.SerializeToString,
            ai__pb2.IndexingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
